name: Chequeo Visa Australia

on:
  # Esto hace que se ejecute cada 30 minutos. Es lo mínimo que permite GitHub Actions.
  schedule:
    - cron: '*/30 * * * *'
  # Esto te permite ejecutarlo manualmente desde la pestaña Actions para probar.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Clona tu repositorio para tener acceso a los archivos
    - uses: actions/checkout@v3

    # 2. Configura Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3. Instala las dependencias del archivo requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Ejecuta tu script de Python
    - name: Run Visa Checker
      # Aquí configuramos la variable de entorno con el Secret de GitHub
          env:
            IFTTT_WEBHOOK_URL: ${{ secrets.IFTTT_WEBHOOK_URL }}
          run: python visa_checker.py
