name: Chequeo Visa Australia

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    # AÑADE ESTA SECCIÓN DE PERMISOS
    permissions:
      # Da permiso para leer el contenido del repo
      contents: read
      # Da permiso para modificar los workflows
      actions: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Visa Checker
      env:
        IFTTT_WEBHOOK_URL: ${{ secrets.IFTTT_WEBHOOK_URL }}
        # NECESITAMOS EL TOKEN DE GITHUB PARA LA API
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # NECESITAMOS EL NOMBRE DEL REPOSITORIO Y EL ID DEL WORKFLOW
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_WORKFLOW_ID: ${{ github.workflow_id }}
      run: python visa_checker.py
